version: '2.4'
services:
  nc-hello-world:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      - TEXT=sup bruh
      - LOCALE=en_US
      - TZ=America/Chicago

  nc-hello-world-haproxy:
    image: "haproxy:2.3"
    ports:
      - "9001:80"
    volumes_from:
      - nc-hello-world:ro